#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  namespace: udacity
  labels:
    app: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: #@ data.values.image
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%

---      
apiVersion: v1
kind: Service
metadata:
  name: capstone-svc
  namespace: udacity
spec:
  selector:
    app: capstone
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: capstone-ing
  namespace: udacity
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: capstone-svc
              servicePort: 8080